# Max 16 characters in keyboard name
CONFIG_ZMK_KEYBOARD_NAME="crkbd"

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

CONFIG_PM_DEVICE=y
CONFIG_ZMK_SLEEP=n

# ZMK configuration for Corne v3.0.1 (nice!nano v2)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_EFFECT_BREATHE=y
CONFIG_ZMK_RGB_UNDERGLOW_BRIGHTNESS=60
CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=8
CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=8
CONFIG_ZMK_RGB_UNDERGLOW_VAL_STEP=8
CONFIG_ZMK_SPLIT_ROLE_STATIC=y

# Set the number of BLE peripherals (e.g., 1 for unibody, 2 for split)
# Set BT_MAX_CONN to ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS + desired BT profiles (default 5)
# BT_MAX_CONN and BT_MAX_PAIRED should match
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Enable battery level fetching and proxying for split BLE central peripherals
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y


